image: gitpod/workspace-full

# Commands that will run on workspace start
tasks:
    - name: Setup, Install & Build
      before: yarn global add express
      init: yarn install
      command: node index.js
      env: 
        HTTP_PORT: 3001

# Ports to expose on workspace startup
ports:
    - port: 3001
      onOpen: open-preview
      name: WebUI
      description: Lightweight WebInterface
      visibility: public
      protocol: http